databases:
  - name: photography_site
    databaseName: photography_site
    user: henryescobar

services:
  - type: web
    name: photography_site
    runtime: ruby
    env: production
    repo: https://github.com/pnw-henry/photography-site-render
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: photography_site
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
